//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace Models
{
	/// <summary>
	/// Database       : Inventory
	/// Data Source    : Inventory
	/// Server Version : 3.19.3
	/// </summary>
	public partial class InventoryDB : LinqToDB.Data.DataConnection
	{
		public ITable<Client>          Clients          { get { return this.GetTable<Client>(); } }
		public ITable<ClientAccount>   ClientAccounts   { get { return this.GetTable<ClientAccount>(); } }
		public ITable<Farmer>          Farmers          { get { return this.GetTable<Farmer>(); } }
		public ITable<Good>            Goods            { get { return this.GetTable<Good>(); } }
		public ITable<Log>             Logs             { get { return this.GetTable<Log>(); } }
		public ITable<Master>          Masters          { get { return this.GetTable<Master>(); } }
		public ITable<Purchase>        Purchases        { get { return this.GetTable<Purchase>(); } }
		public ITable<Retail>          Retails          { get { return this.GetTable<Retail>(); } }
		public ITable<Stock>           Stocks           { get { return this.GetTable<Stock>(); } }
		public ITable<Supplier>        Suppliers        { get { return this.GetTable<Supplier>(); } }
		public ITable<SupplierAccount> SupplierAccounts { get { return this.GetTable<SupplierAccount>(); } }
		public ITable<Wholesale>       Wholesales       { get { return this.GetTable<Wholesale>(); } }

		public void InitMappingSchema()
		{
		}

		public InventoryDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public InventoryDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext();
	}

	[Table("client")]
	public partial class Client
	{
		[Column("clientID"),      PrimaryKey,  Identity] public long   ClientID      { get; set; } // integer
		[Column("name"),          NotNull              ] public string Name          { get; set; } // text(max)
		[Column("phone"),            Nullable          ] public string Phone         { get; set; } // text(max)
		[Column("address"),          Nullable          ] public string Address       { get; set; } // text(max)
		[Column("storeName"),        Nullable          ] public string StoreName     { get; set; } // text(max)
		[Column("businessPlace"),    Nullable          ] public string BusinessPlace { get; set; } // text(max)
		[Column("storagePlace"),     Nullable          ] public string StoragePlace  { get; set; } // text(max)
		[Column("email"),            Nullable          ] public string Email         { get; set; } // text(max)
		[Column("creditCode"),       Nullable          ] public string CreditCode    { get; set; } // text(max)

		#region Associations

		/// <summary>
		/// FK_clientAccount_0_0_BackReference
		/// </summary>
		[Association(ThisKey="ClientID", OtherKey="ClientID", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ClientAccount> ClientAccounts { get; set; }

		/// <summary>
		/// FK_wholesale_1_0_BackReference
		/// </summary>
		[Association(ThisKey="ClientID", OtherKey="ClientID", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Wholesale> Wholesales { get; set; }

		#endregion
	}

	[Table("clientAccount")]
	public partial class ClientAccount
	{
		[Column("clientAccountID"), PrimaryKey, Identity] public long   ClientAccountID      { get; set; } // integer
		[Column("clientAccount"),   NotNull             ] public double ClientAccount_Column { get; set; } // real
		[Column("clientID"),        NotNull             ] public long   ClientID             { get; set; } // integer
		[Column("dataTime"),        NotNull             ] public string DataTime             { get; set; } // text(max)

		#region Associations

		/// <summary>
		/// FK_clientAccount_0_0
		/// </summary>
		[Association(ThisKey="ClientID", OtherKey="ClientID", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_clientAccount_0_0", BackReferenceName="ClientAccounts")]
		public Client Client { get; set; }

		#endregion
	}

	[Table("farmer")]
	public partial class Farmer
	{
		[Column("farmerID"), PrimaryKey, Identity] public long   FarmerID { get; set; } // integer
		[Column("name"),     Nullable            ] public string Name     { get; set; } // text(max)
		[Column("phone"),    Nullable            ] public string Phone    { get; set; } // text(max)
		[Column("number"),   Nullable            ] public string Number   { get; set; } // text(max)
		[Column("province"), Nullable            ] public string Province { get; set; } // text(max)
		[Column("city"),     Nullable            ] public string City     { get; set; } // text(max)
		[Column("county"),   Nullable            ] public string County   { get; set; } // text(max)
		[Column("town"),     Nullable            ] public string Town     { get; set; } // text(max)
		[Column("village"),  Nullable            ] public string Village  { get; set; } // text(max)

		#region Associations

		/// <summary>
		/// FK_retail_1_0_BackReference
		/// </summary>
		[Association(ThisKey="FarmerID", OtherKey="FarmerID", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Retail> Retails { get; set; }

		#endregion
	}

	[Table("goods")]
	public partial class Good
	{
		[Column(),        PrimaryKey,  Identity] public long    商品ID      { get; set; } // integer
		[Column(),        NotNull              ] public string  商品追溯码前11位 { get; set; } // text(max)
		[Column("_商品名称"), NotNull              ] public string  商品名称      { get; set; } // text(max)
		[Column(),           Nullable          ] public double? 进货价格      { get; set; } // real
		[Column(),           Nullable          ] public double? 批发价格      { get; set; } // real
		[Column(),           Nullable          ] public double? 零售价格      { get; set; } // real
		[Column("单位(大)"), NotNull              ] public string  单位大       { get; set; } // text(max)
		[Column(),        NotNull              ] public long    内含量       { get; set; } // integer
		[Column("单位(小)"), NotNull              ] public string  单位小       { get; set; } // text(max)
		[Column("种类(大)"), NotNull              ] public string  种类大       { get; set; } // text(max)
		[Column("种类(小)"), NotNull              ] public string  种类小       { get; set; } // text(max)
		[Column(),           Nullable          ] public string  主要成分      { get; set; } // text(max)
		[Column(),        NotNull              ] public string  是否高毒      { get; set; } // text(max)
		[Column(),        NotNull              ] public string  生产厂家      { get; set; } // text(max)
		[Column(),           Nullable          ] public double? 箱重量       { get; set; } // real
		[Column(),           Nullable          ] public double? 瓶重量       { get; set; } // real
		[Column(),           Nullable          ] public string  农药登记证号    { get; set; } // text(max)
	}

	[Table("log")]
	public partial class Log
	{
		[Column("logID"),       PrimaryKey, NotNull] public long   LogID       { get; set; } // integer
		[Column("logContent"),              NotNull] public string LogContent  { get; set; } // text(max)
		[Column("logDateTime"),             NotNull] public string LogDateTime { get; set; } // text(max)
		[Column("logAction"),               NotNull] public string LogAction   { get; set; } // text(max)
	}

	[Table("master")]
	public partial class Master
	{
		[Column("payee"),    PrimaryKey,  NotNull] public string Payee    { get; set; } // text(max)
		[Column("phone"),                 NotNull] public string Phone    { get; set; } // text(max)
		[Column("email"),       Nullable         ] public string Email    { get; set; } // text(max)
		[Column("wechat"),      Nullable         ] public string Wechat   { get; set; } // text(max)
		[Column("password"),              NotNull] public string Password { get; set; } // text(max)
		[Column("username"),              NotNull] public string Username { get; set; } // text(max)

		#region Associations

		/// <summary>
		/// FK_purchase_0_0_BackReference
		/// </summary>
		[Association(ThisKey="Payee", OtherKey="Payee", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Purchase> Purchases { get; set; }

		/// <summary>
		/// FK_retail_0_0_BackReference
		/// </summary>
		[Association(ThisKey="Payee", OtherKey="Payee", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Retail> Retails { get; set; }

		/// <summary>
		/// FK_wholesale_0_0_BackReference
		/// </summary>
		[Association(ThisKey="Payee", OtherKey="Payee", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Wholesale> Wholesales { get; set; }

		#endregion
	}

	[Table("purchase")]
	public partial class Purchase
	{
		[Column("purchaseID"), PrimaryKey, Identity] public long   PurchaseID   { get; set; } // integer
		[Column("code"),       NotNull             ] public string Code         { get; set; } // text(max)
		[Column("datatime"),   NotNull             ] public string Datatime     { get; set; } // text(max)
		[Column("storeName"),  NotNull             ] public string StoreName    { get; set; } // text(max)
		[Column("goodsID"),    NotNull             ] public long   GoodsID      { get; set; } // integer
		[Column(),             NotNull             ] public double RealPrice    { get; set; } // real
		[Column(),             NotNull             ] public double NumBigUnit   { get; set; } // real
		[Column(),             NotNull             ] public long   NumSmallUnit { get; set; } // integer
		[Column(),             NotNull             ] public double SumPrice     { get; set; } // real
		[Column("isReturn"),   NotNull             ] public long   IsReturn     { get; set; } // integer
		[Column("supplierID"), NotNull             ] public long   SupplierID   { get; set; } // integer
		[Column("payee"),      NotNull             ] public string Payee        { get; set; } // text(max)

		#region Associations

		/// <summary>
		/// FK_purchase_0_0
		/// </summary>
		[Association(ThisKey="Payee", OtherKey="Payee", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_purchase_0_0", BackReferenceName="Purchases")]
		public Master Master { get; set; }

		/// <summary>
		/// FK_purchase_1_0
		/// </summary>
		[Association(ThisKey="SupplierID", OtherKey="SupplierID", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_purchase_1_0", BackReferenceName="Purchases")]
		public Supplier Supplier { get; set; }

		#endregion
	}

	[Table("retail")]
	public partial class Retail
	{
		[Column("retailID"),  PrimaryKey, Identity] public long   RetailID     { get; set; } // integer
		[Column("code"),      NotNull             ] public string Code         { get; set; } // text(max)
		[Column("datatime"),  NotNull             ] public string Datatime     { get; set; } // text(max)
		[Column("storeName"), NotNull             ] public string StoreName    { get; set; } // text(max)
		[Column("goodsID"),   NotNull             ] public long   GoodsID      { get; set; } // integer
		[Column(),            NotNull             ] public double RealPrice    { get; set; } // real
		[Column(),            NotNull             ] public double NumBigUnit   { get; set; } // real
		[Column(),            NotNull             ] public long   NumSmallUnit { get; set; } // integer
		[Column(),            NotNull             ] public double SumPrice     { get; set; } // real
		[Column("isReturn"),  NotNull             ] public long   IsReturn     { get; set; } // integer
		[Column("farmerID"),  NotNull             ] public long   FarmerID     { get; set; } // integer
		[Column("payee"),     NotNull             ] public string Payee        { get; set; } // text(max)

		#region Associations

		/// <summary>
		/// FK_retail_1_0
		/// </summary>
		[Association(ThisKey="FarmerID", OtherKey="FarmerID", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_retail_1_0", BackReferenceName="Retails")]
		public Farmer Farmer { get; set; }

		/// <summary>
		/// FK_retail_0_0
		/// </summary>
		[Association(ThisKey="Payee", OtherKey="Payee", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_retail_0_0", BackReferenceName="Retails")]
		public Master Master { get; set; }

		#endregion
	}

	[Table("stock")]
	public partial class Stock
	{
		[Column("stockID"),   PrimaryKey, Identity] public long   StockID      { get; set; } // integer
		[Column("storeName"), NotNull             ] public string StoreName    { get; set; } // text(max)
		[Column("goodsID"),   NotNull             ] public long   GoodsID      { get; set; } // integer
		[Column(),            NotNull             ] public double NumBigUnit   { get; set; } // real
		[Column(),            NotNull             ] public long   NumSmallUnit { get; set; } // integer
	}

	[Table("supplier")]
	public partial class Supplier
	{
		[Column("supplierID"), PrimaryKey,  Identity] public long   SupplierID      { get; set; } // integer
		[Column("supplier"),   NotNull              ] public string Supplier_Column { get; set; } // text(max)
		[Column("contact"),    NotNull              ] public string Contact         { get; set; } // text(max)
		[Column("phone"),         Nullable          ] public string Phone           { get; set; } // text(max)
		[Column("fax"),           Nullable          ] public string Fax             { get; set; } // text(max)
		[Column("email"),         Nullable          ] public string Email           { get; set; } // text(max)
		[Column("address"),       Nullable          ] public string Address         { get; set; } // text(max)
		[Column("nature"),        Nullable          ] public string Nature          { get; set; } // text(max)
		[Column("legal"),         Nullable          ] public string Legal           { get; set; } // text(max)
		[Column("bank"),          Nullable          ] public string Bank            { get; set; } // text(max)
		[Column("bankAccout"),    Nullable          ] public string BankAccout      { get; set; } // text(max)
		[Column("remarks"),       Nullable          ] public string Remarks         { get; set; } // text(max)

		#region Associations

		/// <summary>
		/// FK_purchase_1_0_BackReference
		/// </summary>
		[Association(ThisKey="SupplierID", OtherKey="SupplierID", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Purchase> Purchases { get; set; }

		/// <summary>
		/// FK_supplierAccount_0_0_BackReference
		/// </summary>
		[Association(ThisKey="SupplierID", OtherKey="SupplierID", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<SupplierAccount> SupplierAccounts { get; set; }

		#endregion
	}

	[Table("supplierAccount")]
	public partial class SupplierAccount
	{
		[Column("supplierAccountID"), PrimaryKey,  Identity] public long    SupplierAccountID      { get; set; } // integer
		[Column("supplierID"),        NotNull              ] public long    SupplierID             { get; set; } // integer
		[Column("datetime"),             Nullable          ] public string  Datetime               { get; set; } // text(max)
		[Column("supplierAccount"),      Nullable          ] public double? SupplierAccount_Column { get; set; } // real

		#region Associations

		/// <summary>
		/// FK_supplierAccount_0_0
		/// </summary>
		[Association(ThisKey="SupplierID", OtherKey="SupplierID", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_supplierAccount_0_0", BackReferenceName="SupplierAccounts")]
		public Supplier Supplier { get; set; }

		#endregion
	}

	[Table("wholesale")]
	public partial class Wholesale
	{
		[Column("wholesaleID"), PrimaryKey, Identity] public long   WholesaleID  { get; set; } // integer
		[Column("code"),        NotNull             ] public string Code         { get; set; } // text(max)
		[Column("datatime"),    NotNull             ] public string Datatime     { get; set; } // text(max)
		[Column("storeName"),   NotNull             ] public string StoreName    { get; set; } // text(max)
		[Column("goodsID"),     NotNull             ] public long   GoodsID      { get; set; } // integer
		[Column(),              NotNull             ] public double RealPrice    { get; set; } // real
		[Column(),              NotNull             ] public double NumBigUnit   { get; set; } // real
		[Column(),              NotNull             ] public long   NumSmallUnit { get; set; } // integer
		[Column(),              NotNull             ] public double SumPrice     { get; set; } // real
		[Column("isReturn"),    NotNull             ] public long   IsReturn     { get; set; } // integer
		[Column("clientID"),    NotNull             ] public long   ClientID     { get; set; } // integer
		[Column("payee"),       NotNull             ] public string Payee        { get; set; } // text(max)

		#region Associations

		/// <summary>
		/// FK_wholesale_1_0
		/// </summary>
		[Association(ThisKey="ClientID", OtherKey="ClientID", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_wholesale_1_0", BackReferenceName="Wholesales")]
		public Client Client { get; set; }

		/// <summary>
		/// FK_wholesale_0_0
		/// </summary>
		[Association(ThisKey="Payee", OtherKey="Payee", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_wholesale_0_0", BackReferenceName="Wholesales")]
		public Master Master { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Client Find(this ITable<Client> table, long ClientID)
		{
			return table.FirstOrDefault(t =>
				t.ClientID == ClientID);
		}

		public static ClientAccount Find(this ITable<ClientAccount> table, long ClientAccountID)
		{
			return table.FirstOrDefault(t =>
				t.ClientAccountID == ClientAccountID);
		}

		public static Farmer Find(this ITable<Farmer> table, long FarmerID)
		{
			return table.FirstOrDefault(t =>
				t.FarmerID == FarmerID);
		}

		public static Good Find(this ITable<Good> table, long 商品ID)
		{
			return table.FirstOrDefault(t =>
				t.商品ID == 商品ID);
		}

		public static Log Find(this ITable<Log> table, long LogID)
		{
			return table.FirstOrDefault(t =>
				t.LogID == LogID);
		}

		public static Master Find(this ITable<Master> table, string Payee)
		{
			return table.FirstOrDefault(t =>
				t.Payee == Payee);
		}

		public static Purchase Find(this ITable<Purchase> table, long PurchaseID)
		{
			return table.FirstOrDefault(t =>
				t.PurchaseID == PurchaseID);
		}

		public static Retail Find(this ITable<Retail> table, long RetailID)
		{
			return table.FirstOrDefault(t =>
				t.RetailID == RetailID);
		}

		public static Stock Find(this ITable<Stock> table, long StockID)
		{
			return table.FirstOrDefault(t =>
				t.StockID == StockID);
		}

		public static Supplier Find(this ITable<Supplier> table, long SupplierID)
		{
			return table.FirstOrDefault(t =>
				t.SupplierID == SupplierID);
		}

		public static SupplierAccount Find(this ITable<SupplierAccount> table, long SupplierAccountID)
		{
			return table.FirstOrDefault(t =>
				t.SupplierAccountID == SupplierAccountID);
		}

		public static Wholesale Find(this ITable<Wholesale> table, long WholesaleID)
		{
			return table.FirstOrDefault(t =>
				t.WholesaleID == WholesaleID);
		}
	}
}
